### ISSUE TITLE
Greetings. Issue in applying code

### ISSUE THREAD

**Issue by shahzad2347** [GabauerDavid/PortfolioTechniques#1]
First of all, it is a great effort that you made, salute to you for this wonderful effort, i am facing some issue in implementing minimum connectedness portfolio. error message is   

Error in res[i, ] <- matrix(c(mean(x[, i]), sd(x[, i]), quantile(x[, i]), : 
replacement has length zero

when i traceback, it pertains to following area but i am unable to understand

function(data, H, type="long") {
    k = ncol(data)
    n = nrow(data)
    I = matrix(1,k,1)
    
     values = function(x){
        x = as.matrix(x)
        res = matrix(NA,nrow=ncol(x), ncol=4)
        for (i in 1:ncol(x)){
            res[i,]=matrix(c(mean(x[,i]), sd(x[,i]), quantile(x[,i]),0.05,na.rm=TRUE, quantile(x[,i])),0.95, nrow=1)
        }
        colnames(res)=c("Mean","Std.Dev.","5%","95%")
        res
    }
    
    portfolio_weights = matrix(NA,nrow=n,ncol=k)
    for (i in 1:n) {
        Vinv = solve(H[,,i])
        portfolio_weights[i,] = (Vinv%*%I) / c(t(I)%*%Vinv%*%I)
        if (type=="long") {
            portfolio_weights[i,] = ifelse(portfolio_weights[i,]<0,0,portfolio_weights[i,])
            portfolio_weights[i,] = ifelse(portfolio_weights[i,]>1,1,portfolio_weights[i,])
            portfolio_weights[i,] = portfolio_weights[i,] / sum(portfolio_weights[i,])
        }
    }
    summary = NULL
    for (i in 1:k) {
        summary = rbind(summary, values(portfolio_weights[,i]))
    }
    rownames(summary)=colnames(data)
    
    cumulative_ratio = f_statistics = pval = HE = matrix(NA,ncol=1,nrow=k)
    rownames(cumulative_ratio)=rownames(f_statistics)=rownames(pval)=rownames(HE)=colnames(data)
    cumulative_asset_return = matrix(NA,ncol=k,nrow=n)
    portfolio_return = matrix(NA,ncol=1,nrow=n)
    for (i in 1:n) {
        portfolio_return[i,] = sum(portfolio_weights[i,]*as.numeric(data[i,]))
    }
    cumulative_portfolio_return = cumsum(portfolio_return)
    
    for (i in 1:k) {
        HE[i,] = 1 - var(portfolio_return)/var(data[,i])
        xxx = rbind(cbind(portfolio_return,1),cbind(data[,i],2))
        dfpval = data.frame(val=xxx[,1],group=as.character(xxx[,2]))
        pval[i,] = fligner.test(val~group,dfpval)$p.val
        cumulative_asset_return[,i] = cumsum(data[,i])
        cumulative_ratio[i,] = cumulative_portfolio_return[length(cumulative_portfolio_return)]/cumulative_asset_return[nrow(cumulative_asset_return),i]
    }
    table = cbind(summary,HE,pval)
    colnames(table)=c("Mean","Std.Dev.","5%","95%","HE","p-value")
    
    return = list(portfolio_weights=portfolio_weights, summary=format(round(table,2),nsmall=2), hedging_effectiveness=HE, pvalue=pval, portfolio_return=portfolio_return, cumulative_portfolio_return=cumulative_portfolio_return, cumulative_asset_return=cumulative_asset_return)
}

**Comment by GabauerDavid** [comment]
Sorry this is an old repository and I will delete it soon. The minimum connectedness portfolio technique has been implemented in the R-Package „ConnectednessApproach“. Please have a look. Best, David
